config/routes.rb
Rails.application.routes.draw do


root 'top#index'

scope "/:locale", locale: /en|ja/   do

  get '' => 'top#index', as: 'top'
  get 'porter' => 'porter#top', as: 'porter_top'
  get 'help' => 'help#index', as: 'help_index'
  get 'inbox' => 'inbox#index', as: "inbox_index"
  get 'inbox/:id' => 'inbox#show', as: "inbox_personal"

  resources :messageboxes, only: [:create, :destroy]
  resources :messages, only: [:create]
  resources :demandposts do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :users, only: [:show, :edit, :update]

  # devise_scope :user do
  #   delete :sign_out, to: 'devise/session#destroy', as: :destroy_user_session
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

  devise_for :users,  controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  # , skip: [:session, :registrations]
  # devise_scope :user do
  #   post "/users/sign_in",    :to => "devise/sessions#create",   :as => 'user_session'
  #   delete "/users/sign_out", :to => "devise/sessions#destroy",  :as => 'destroy_session'
  #   get "/users/edit",        :to => "devise/registrations#edit",  :as => 'edit_user_registration'
  #   put "/users/edit",        :to => "devise/registrations#update",  :as => 'user_registration'
  #   delete "/users/edit",     :to => "devise/registrations#destroy",  :as => nil
  #   post "/users/edit",       :to => "devise/registrations#create",  :as => nil
  # end
  post 'itineraries' => 'itineraries#create', as: "itineraries"
  delete 'itineraries/:id' => 'itineraries#destroy', as: "itinerary"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/demandpost.rb
class Demandpost < ApplicationRecord
  belongs_to :user

  validates :city_to, presence: true
  validates :country_from, presence: true
  validates :item_description, presence: true
  validates :reward_description, presence: true

end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
  belongs_to :user
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user_from, class_name: 'User'
  belongs_to :user_to, class_name: 'User'
  belongs_to :messagebox
  
  validates :content, presence: true
  validates :user_from_id, presence: true
  validates :user_to_id, presence: true
end

app/models/messagebox.rb
class Messagebox < ApplicationRecord
  has_many :messages
  has_many :usercontacts
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :confirmable

  has_many :demandposts, dependent: :destroy

  has_many :send_messages, class_name: 'Message', foreign_key: 'user_from_id'
  has_many :recieve_messages, class_name: 'Message', foreign_key: 'user_to_id'

  has_many :usercontacts
  has_many :itineraries

  attr_reader :avatar_remote_url
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}, default_url: "profile-default.jpg"
  validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]


  def avatar_remote_url=(url_value)
    self.avatar = URI.parse(url_value)
    # Assuming url_value is http://example.com/photos/face.png
    # avatar_file_name == "face.png"
    # avatar_content_type == "image/png"
    @avatar_remote_url = url_value
  end

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        password: Devise.friendly_token[0, 20],
        confirmed_at: Time.now.utc,
        confirmation_token: nil,
        name:     auth.info.name,
        avatar: auth.info.image
      )
    end

    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

end

app/models/usercontact.rb
class Usercontact < ApplicationRecord
  belongs_to :user
  belongs_to :contacted, class_name: 'User'
  belongs_to :messagebox
  has_many :messages, through: :messagebox

  validates :user_id, presence: true
  validates :contacted, presence: true
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  def index
  end
end

app/controllers/inbox_controller.rb
class InboxController < ApplicationController
  before_action :authenticate_user!

  def index
    usercontacts = Usercontact.where(user_id: current_user.id).includes(:messages, :contacted)
    @users = []
    @lastmessages = []
    usercontacts.each do |usercontact|
      @lastmessages << usercontact.messages.order(created_at: :desc).first
      @users << usercontact.contacted
    end
    @array = @users.zip(@lastmessages)
  end

  def show
    # check if the user has the access to this messagebox
    usercontact = Usercontact.find_by(messagebox_id: params[:id], user_id: current_user.id)
    if usercontact.nil?
      redirect_to root_path
    else
      @messages = Message.where(messagebox_id: params[:id]).order(created_at: :desc)
      @user = Usercontact.find_by(messagebox_id: params[:id], user_id: current_user.id).contacted
    end
  end
end

app/controllers/porter_controller.rb
class PorterController < ApplicationController
  def top
    @search = Demandpost.search(params[:q])

    if user_signed_in?
      @demandposts = current_user.demandposts.includes(:offers, :comments)
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
    if user_signed_in?
      @demandposts = Demandpost.last(5)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :confirm_user, only: [:edit, :update]

  def show

  end

  def edit
    @itinerary = Itinerary.new
    registered_itineraries = Itinerary.where(user_id: params[:id])
    # there should be a better way to express this...
    @my_itineraries = []
    registered_itineraries.each do |itinerary|
      @my_itineraries << itinerary if itinerary.departure_date > Date.today
    end
  end

  def update
    current_user.update(update_params)
    redirect_to edit_user_path(current_user)
  end

  private
  def update_params
    params.require(:user).permit(:name, :home_town, :avatar, :message_notification, :request_notification)
  end

  def confirm_user
    redirect_to root_path unless current_user == User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/demandposts_helper.rb
module DemandpostsHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/inbox_helper.rb
module InboxHelper
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/helpers/messageboxes_helper.rb
module MessageboxesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/porter_helper.rb
module PorterHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/help/index.html.erb
<h1>Help#index</h1>
<p>Find me in app/views/help/index.html.erb</p>

app/views/inbox/index.html.erb
<div class="body-padding">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <h2><%= t('.messages') %></h2>
        <hr class="blackborder">
        <% unless @array.any? %>
        <p><%= t('.no_message') %></p>
        <% end %>
        <% @array.each do |user, lastmessage| %>
        <%= link_to inbox_personal_path(lastmessage.messagebox_id), class: "post" do %>
          <div class="row">
            <div class="col-md-2">
              <%= image_tag user.avatar.url(:medium), class: "avatarsmall center-block"%>
            </div>
            <div class="col-md-3">
              <div class="text-center">
                <div class="profile-font-name-small"><%= user.name %></div>
                <div class="profile-font-town-small"><%= user.home_town %></div>
                <div class="profile-font-town-small"><%= I18n.l Date.parse(lastmessage.created_at.to_s) %></div>
              </div>
            </div>
            <div class="col-md-7 message-extract-layout">
              <div class="message-extract-font"><p><%= lastmessage.content%></p></div>
            </div>
          </div>
        <% end %>
        <hr class="blackborder">

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/inbox/show.html.erb
<div class="body-padding">
  <div class="container">
    <div class="row">
      <div class="col-md-9 col-md-offset-1">

        <br>
        <div class="row">
          <div class="col-md-4">
            <div class="row">
              <div class="col-md-12">
                <%= image_tag @user.avatar.url(:medium), class: "avatarlarge center-block"%>
              </div>
              <div class="text-center col-md-12">
                <div class="profile-font-name"><%= @user.name %></div>
                <div class="profile-font-town"><%= @user.home_town %></div>
              </div>
            </div>
          </div>
          <div class="col-md-8">

            <%= form_tag(messages_path(user_to_id: @user.id, initial_message: false), method: :post) do %>
            <textarea type="text" , name="content" cols="30" rows="8" placeholder="<%= t('.send_placeholder')%>"></textarea><br>
            <%= submit_tag t('.send_button'), class:  "btn btn-primary" %>
            <% end %>
            <hr class="blackborder">
            <% @messages.each do |message| %>
            <div class="row">
              <% if message.user_from_id == current_user.id %>
              <div class="col-xs-9">
                <div class="message-box-from">
                  <div class="message-content">
                    <%= message.content %>
                  </div>
                </div>
              </div>
              <div class="col-xs-3">
                <%= image_tag current_user.avatar.url(:medium), class: "avatarnano center-block"%>
              </div>
            <% else %>
              <div class="col-xs-3">
                <%= image_tag @user.avatar.url(:medium), class: "avatarnano center-block"%>
              </div>
              <div class="col-xs-9">
                <div class="message-box-to">
                  <div class="message-content">
                    <%= message.content %>
                  </div>
                </div>
              </div>
              <% end %>
            </div>
            <hr class="transparent">
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/porter/top.html.erb
<% if user_signed_in? %>
<div class="porter-top-signed">
  <div class="header-content">
    <div class="header-content-inner">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <h1><%= t '.toptitle'%></h1>
          <p class="fine"><%= t '.subtitle'%></p>
            <%= search_form_for @search, url: demandposts_path, method: :get do |f| %>
            <div class="form-inline">
              <div class="form-group">
                <%= f.country_select :country_from_eq, {priority: %w(US CA), prompt: t('.fromcountrytab')}, class: "form-control" %>
                <%= f.text_field :city_to_cont, id: "city_to", class: "form-control", placeholder: t('.tocitytab') %>
              </div>
            </div>
            <br>
            <div class="form-group">
              <%= f.submit t('.searchbutton'), class: "btn btn-primary" %>
            </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% else %>
<div class="porter-top-unsigned">
  <div class="header-content">
    <div class="header-content-inner">
      <div class="row">
        <div class="col-lg-6">
          <h1><%= t '.toptitle'%></h1>
          <hr>
          <p><%= t '.subtitle'%></p>
          <a class="page-scroll btn btn-primary btn-xl sr-button" role="button" data-toggle="modal" data-target="#signup-modal" data-backdrop="static" data-controls-modal="signup-modal">
            <b><%= t '.signupbutton'%></b>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>


<div class="land-list-section">
  <div class="text-center">
    <h3><%= t '.flow'%></h3>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-offset-1 col-lg-10 col-lg-1-offset">
        <h2>1.</h2>
        <h2><%= t '.flowtitle1'%></h2>
        <h5><%= t '.flowsubtitle1'%></h5>

        <div class="row">
          <div class="col-lg-4 col-md-6">
            <div class="service-box">
              <i class="fa fa-2x fa-search text-primary sr-icons"></i>
              <h3><%= t '.flowhead11'%></h3>
              <p class="fine"><%= t '.flowcontent11'%></p>
            </div>
          </div>
          <div class="col-lg-4 col-md-6">
            <div class="service-box">
              <i class="fa fa-2x fa-list-alt text-primary sr-icons"></i>
              <h3><%= t '.flowhead12'%></h3>
              <p class="fine"><%= t '.flowcontent12'%></p>
            </div>
          </div>
          <div class="col-lg-4 col-md-6">
            <div class="service-box">
              <i class="fa fa-2x fa-gift text-primary sr-icons"></i>
              <h3><%= t '.flowhead13'%></h3>
              <p class="fine"><%= t '.flowcontent13'%></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="land-list-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-offset-1 col-lg-10 col-lg-1-offset">
        <h2>2.</h2>
        <h2><%= t '.flowtitle2'%></h2>
        <h5><%= t '.flowsubtitle2'%></h5>
        <div class="row">
          <div class="col-lg-4 col-md-6">
            <div class="service-box">
              <i class="fa fa-2x fa-commenting-o text-primary sr-icons"></i>
              <h3><%= t '.flowhead21'%></h3>
              <p class="fine"><%= t '.flowcontent21'%></p>
            </div>
          </div>
          <div class="col-lg-4 col-md-6">
            <div class="service-box">
              <i class="fa fa-2x fa-suitcase text-primary sr-icons"></i>
              <h3><%= t '.flowhead22'%></h3>
              <p class="fine"><%= t '.flowcontent22'%></p>
            </div>
          </div>
          <div class="col-lg-4 col-md-6">
            <div class="service-box">
              <i class="fa fa-2x fa-location-arrow text-primary sr-icons"></i>
              <h3><%= t '.flowhead23'%></h3>
              <p class="fine"><%= t '.flowcontent23'%></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="land-list-section">
  <div class="container">
    <div class="row">
      <div class="col-lg-offset-1 col-lg-10 col-lg-1-offset">
        <h2>3.</h2>
        <h2><%= t '.flowtitle3'%></h2>
        <h5><%= t '.flowsubtitle3'%></h5>
        <div class="row">
          <div class="col-lg-4 col-md-6">
            <div class="service-box">
              <i class="fa fa-2x fa-handshake-o text-primary sr-icons"></i>
              <h3><%= t '.flowhead31'%></h3>
              <p class="fine"><%= t '.flowcontent31'%></p>
            </div>
          </div>
          <div class="col-lg-4 col-md-6">
            <div class="service-box">
              <i class="fa fa-2x fa-money text-primary sr-icons"></i>
              <h3><%= t '.flowhead32'%></h3>
              <p class="fine"><%= t '.flowcontent32'%></p>
            </div>
          </div>
          <div class="col-lg-4 col-md-6">
            <div class="service-box">
              <i class="fa fa-2x fa-cutlery text-primary sr-icons"></i>
              <h3><%= t '.flowhead33'%></h3>
              <p class="fine"><%= t '.flowcontent33'%></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<% unless user_signed_in? %>
<div class="container">
  <div class="row">
    <div class="col-xs-offset-2 col-xs-8 col-xs-2-offset col-lg-offset-4 col-lg-4 col-lg-4-offset">
      <a class="btn btn-primary btn-xl sr-button center-block" role="button" data-toggle="modal" data-target="#signup-modal" data-backdrop="static" data-controls-modal="signup-modal">
        <b><%= t '.signupbutton'%></b>
      </a>
    </div>
  </div>
</div>
<% end %>

<hr class="sectionborder bg-ghostwhite">

<div class="bg-lavender">
  <div class="container text-center">
    <div class="call-to-action">
      <h3><%= t 'top._nonsigned.legaltitle'%></h3>
      <p><%= t 'top._nonsigned.legalcontent'%></p>
    </div>
  </div>
</div>

<div class="modal fade index" id="signup-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog animated">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
      </div>
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <h4>Sign up</h4>
          <div class="text-center">
          <div class="social-buttons-signup">
            <a href="<%= omniauth_authorize_path(resource_name, "facebook") %>" class="btn btn-fb">
              <i class="fa fa-facebook"></i>
              Facebook</a>
          </div>
          <br>
          -------- or -------
          <br>
        </div>
          <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <%= devise_error_messages! %>
            <div class="form-group">
              <div class="field">
                <%= f.label :email, "Email address" %><br/>
                <%= f.email_field :email, class: "form-control", autofocus: true, placeholder: "Email address" %>
              </div>
            </div>
            <div class="form-group">

              <%= f.label :password, "password"%><br/>
              <%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "Password (more than 5 characters)" %>
            </div>

            <div class="form-group">
              <%= f.label :password_confirmation %><br/>
              <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.submit "Sign up", class: "btn btn-primary btn-block" %>
            </div>

          <% end %>

        </div>
      </div>

    </div>
  </div>
</div>

app/views/top/_signed.html.erb
<div class="body-padding">
  <div class="section-top">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <h2><%= t 'top._signed.toptitle'%></h2>
          <p class="fine"><%= t 'top._signed.subtitle'%></p>
          <%= link_to  t('top._signed.titlebutton'), new_demandpost_path, class:"btn btn-primary btn-large center-block" %>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <h3><%= t 'top._signed.requesttitle' %></h3>

        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th><%= t('top._signed.countryfrom_title')%></th>
                <th><%= t('top._signed.item_title')%></th>
                <th><%= t('top._signed.reward_title')%></th>
              </tr>
            </thead>
            <tbody>
              <% @demandposts.each do |demandpost| %>
              <tr data-link="<%= demandpost_path(demandpost.id) %>">
                <td class="request-extract"><%= ISO3166::Country.new(demandpost.country_from).name %></td>
                <td class="request-extract"><%= demandpost.item_description %></td>
                <td class="request-extract"><%= demandpost.reward_description %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
          <%= link_to t('top._signed.requestall'), demandposts_path, class: "pull-right" %>
        </div>
        <br>
      </div>
    </div>
  </div>

  <div class="section-tips">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h3><%= t 'top._signed.tipstitle'%></h3>
          <hr class="primary">
        </div>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-4 col-md-4 text-center">
          <div class="service-box">
            <h4><%= t 'top._signed.tipshead1'%></h4>
            <p class="fine"><%= t 'top._signed.tipscontent1'%></p>
          </div>
        </div>
        <div class="col-lg-4 col-md-4 text-center">
          <div class="service-box">
            <h4><%= t 'top._signed.tipshead2'%></h4>
            <p class="fine"><%= t 'top._signed.tipscontent2'%></p>
          </div>
        </div>
        <div class="col-lg-4 col-md-4 text-center">
          <div class="service-box">
            <h4><%= t 'top._signed.tipshead3'%></h4>
            <p class="fine"><%= t 'top._signed.tipscontent3'%></p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="land-list-section">
    <div class="text-center">
      <h3><%= t 'top._nonsigned.flow'%></h3>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-offset-1 col-lg-10 col-lg-1-offset">
          <h3>①</h3>
          <h2><%= t 'top._nonsigned.flowtitle1'%></h2>
          <h5><%= t 'top._nonsigned.flowsubtitle1'%></h5>

          <div class="row">
            <div class="col-lg-4 col-md-6">
              <div class="service-box">
                <i class="fa fa-2x fa-shopping-cart text-primary sr-icons"></i>
                <h3><%= t 'top._nonsigned.flowhead11'%></h3>
                <p class="fine"><%= t 'top._nonsigned.flowcontent11'%></p>
              </div>
            </div>
            <div class="col-lg-4 col-md-6">
              <div class="service-box">
                <i class="fa fa-2x fa-gift text-primary sr-icons"></i>
                <h3><%= t 'top._nonsigned.flowhead12'%></h3>
                <p class="fine"><%= t 'top._nonsigned.flowcontent12'%></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="land-list-section">
    <div class="container">
      <div class="row">
        <div class="col-lg-offset-1 col-lg-10 col-lg-1-offset">
          <h3>②</h3>
          <h2><%= t 'top._nonsigned.flowtitle2'%></h2>
          <h5><%= t 'top._nonsigned.flowsubtitle2'%></h5>
          <div class="row">
            <div class="col-lg-4 col-md-6">
              <div class="service-box">
                <i class="fa fa-2x fa-commenting-o text-primary sr-icons"></i>
                <h3><%= t 'top._nonsigned.flowhead21'%></h3>
                <p class="fine"><%= t 'top._nonsigned.flowcontent21'%></p>
              </div>
            </div>
            <div class="col-lg-4 col-md-6">
              <div class="service-box">
                <i class="fa fa-2x fa-suitcase text-primary sr-icons"></i>
                <h3><%= t 'top._nonsigned.flowhead22'%></h3>
                <p class="fine"><%= t 'top._nonsigned.flowcontent22'%></p>
              </div>
            </div>
            <div class="col-lg-4 col-md-6">
              <div class="service-box">
                <i class="fa fa-2x fa-location-arrow text-primary sr-icons"></i>
                <h3><%= t 'top._nonsigned.flowhead23'%></h3>
                <p class="fine"><%= t 'top._nonsigned.flowcontent23'%></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="land-list-section">
    <div class="container">
      <div class="row">
        <div class="col-lg-offset-1 col-lg-10 col-lg-1-offset">
          <h3>③</h3>
          <h2><%= t 'top._nonsigned.flowtitle3'%></h2>
          <h5><%= t 'top._nonsigned.flowsubtitle3'%></h5>
          <div class="row">
            <div class="col-lg-4 col-md-6">
              <div class="service-box">
                <i class="fa fa-2x fa-handshake-o text-primary sr-icons"></i>
                <h3><%= t 'top._nonsigned.flowhead31'%></h3>
                <p class="fine"><%= t 'top._nonsigned.flowcontent31'%></p>
              </div>
            </div>
            <div class="col-lg-4 col-md-6">
              <div class="service-box">
                <i class="fa fa-2x fa-money text-primary sr-icons"></i>
                <h3><%= t 'top._nonsigned.flowhead32'%></h3>
                <p class="fine"><%= t 'top._nonsigned.flowcontent32'%></p>
              </div>
            </div>
            <div class="col-lg-4 col-md-6">
              <div class="service-box">
                <i class="fa fa-2x fa-cutlery text-primary sr-icons"></i>
                <h3><%= t 'top._nonsigned.flowhead33'%></h3>
                <p class="fine"><%= t 'top._nonsigned.flowcontent33'%></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="section-link-request">
    <div class="section-link-request-content">
      <div class="container">
        <div class="row">
          <div class="col-lg-5 col-xs-10 col-lg-offset-9 col-xs-offset-1 col-xs-1-offset">
            <h1><%= t 'top._signed.requestlinktitle'%></h1>
            <%= link_to  t('top._signed.titlebutton'), new_demandpost_path, class:"btn btn-primary btn-xl"%>
          </div>
        </div>
      </div>
    </div>
  </div>

  <aside class="bg-ghostwhite">
    <div class="container text-center">
      <div class="call-to-action">
        <h3><%= t 'top._signed.legaltitle'%></h3>
        <p class="fine"><%= t 'top._signed.legalcontent'%></p>
      </div>
    </div>
  </aside>

  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-lg-offset-4 text-center">
        <i class="fa fa-envelope-o fa-3x sr-contact"></i>
        <p>
          <a href="mailto:feedback@courcie.com">feedback@courcie.com</a>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/top/index.html.erb
<% if user_signed_in? %>
  <%= render 'signed'%>
<% else %>
  <%= render 'nonsigned'%>
<% end %>