config/routes.rb
Rails.application.routes.draw do


root 'top#index'

scope "/:locale", locale: /en|ja/   do

  get '' => 'top#index', as: 'top'
  get 'porter' => 'porter#top', as: 'porter_top'
  get 'help' => 'help#index', as: 'help_index'
  get 'inbox' => 'inbox#index', as: "inbox_index"
  get 'inbox/:id' => 'inbox#show', as: "inbox_personal"

  resources :messageboxes, only: [:create, :destroy]
  resources :messages, only: [:create]
  resources :demandposts do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :users, only: [:show, :edit, :update]

  # devise_scope :user do
  #   delete :sign_out, to: 'devise/session#destroy', as: :destroy_user_session
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

  devise_for :users,  controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  # , skip: [:session, :registrations]
  # devise_scope :user do
  #   post "/users/sign_in",    :to => "devise/sessions#create",   :as => 'user_session'
  #   delete "/users/sign_out", :to => "devise/sessions#destroy",  :as => 'destroy_session'
  #   get "/users/edit",        :to => "devise/registrations#edit",  :as => 'edit_user_registration'
  #   put "/users/edit",        :to => "devise/registrations#update",  :as => 'user_registration'
  #   delete "/users/edit",     :to => "devise/registrations#destroy",  :as => nil
  #   post "/users/edit",       :to => "devise/registrations#create",  :as => nil
  # end
  post 'itineraries' => 'itineraries#create', as: "itineraries"
  delete 'itineraries/:id' => 'itineraries#destroy', as: "itinerary"


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :confirmable

  has_many :demandposts, dependent: :destroy

  has_many :send_messages, class_name: 'Message', foreign_key: 'user_from_id'
  has_many :recieve_messages, class_name: 'Message', foreign_key: 'user_to_id'

  has_many :usercontacts
  has_many :itineraries

  attr_reader :avatar_remote_url
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}, default_url: "profile-default.jpg"
  validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]


  def avatar_remote_url=(url_value)
    self.avatar = URI.parse(url_value)
    # Assuming url_value is http://example.com/photos/face.png
    # avatar_file_name == "face.png"
    # avatar_content_type == "image/png"
    @avatar_remote_url = url_value
  end

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        password: Devise.friendly_token[0, 20],
        confirmed_at: Time.now.utc,
        confirmation_token: nil,
        name:     auth.info.name,
        avatar: auth.info.image
      )
    end

    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :confirm_user, only: [:edit, :update]

  def show

  end

  def edit
    @itinerary = Itinerary.new
    registered_itineraries = Itinerary.where(user_id: params[:id])
    # there should be a better way to express this...
    @my_itineraries = []
    registered_itineraries.each do |itinerary|
      @my_itineraries << itinerary if itinerary.departure_date > Date.today
    end
  end

  def update
    current_user.update(update_params)
    redirect_to edit_user_path(current_user)
  end

  private
  def update_params
    params.require(:user).permit(:name, :home_town, :avatar, :message_notification, :request_notification)
  end

  def confirm_user
    redirect_to root_path unless current_user == User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="body-padding">
  <div class="row form">
    <div class="col-lg-8 col-lg-offset-2">
      <%= form_for current_user do |f| %>
      <h2 class="text-center"><%= t('.editprofile') %></h2>
      <br>
      <div class="col-lg-4">
        <%= image_tag current_user.avatar.url(:medium), class: "avatarmedium center-block" %>

        <div class="form-group file">
          <%= f.file_field :avatar, class: "form-control floating-label", placeholder: "画像アップロード" %>
        </div>
      </div>
      <div class="col-lg-7 form-horizontal">
        <div class="form-group">
          <%= f.label t('.livingtown'), class: "control-label col-lg-3" %>
          <div class="col-lg-9">
            <%= f.text_field :home_town, placeholder: t('.livingtown_placeholder'), id: :city_from, class: "form-control" %>
          </div>
          <div class="col-lg-offset-3 col-lg-9 profile-show">
            <%= current_user.home_town %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label t('.name'), class: "control-label col-lg-3" %>
          <div class="col-lg-9">
            <%= f.text_field :name, placeholder: t('.name_placeholder'), class: "form-control" %>
          </div>
          <div class="col-lg-offset-3 col-lg-9 profile-show">
            <%= current_user.name %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label t('.notification'), class: "control-label col-lg-3" %>
          <div class="col-lg-9">
            <div class="checkbox-inline">
              <%= f.check_box :request_notification %><%= t('.request_notification')%>
            </div>
            <div class="checkbox-inline">
              <%= f.check_box :message_notification %><%= t('.message_notification')%>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-4 col-lg-offset-4">

      <div class="form-group">
        <%= f.submit t('.submitbutton'), class: "btn btn-primary withripple btn-post center-block" %>
      </div>
      <% end %>
    </div>
  </div>

  <hr class="sectionborder">

  <h2 class="text-center"><%= t('.titleregister') %></h2>
  <p class="fine text-center"><%= t('.subtitleregister') %></p>
  <br>

  <%= form_for @itinerary, class: "form-horizontal" do |f| %>
  <% if @itinerary.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@itinerary.errors.count, "error") %>
      prohibited this itinerary from being saved:</h2>
    <ul>
      <% @itinerary.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="row">
    <div class="col-lg-8 col-lg-offset-3">
      <div class="form-inline">
        <div class="form-group">
          <%= f.country_select :country_from, {priority: %w(US CA), prompt: t('.fromcountrytab')}, class: "form-control" %>
          <%= f.text_field :city_to, id: "city_to", class: "form-control", placeholder: t('.tocitytab') %>
          <div class="input-group date" id='datetimepicker1'>
            <%= f.text_field :departure_date,  class: "form-control", placeholder: t('.departure_date') %>
            <span class="input-group-addon">
              <span class="glyphicon glyphicon-calendar"></span>
            </span>
          </div>
        </div>
        <br>
      </div>
    </div>
  </div>

  <script type="text/javascript">
    $(function () {
      $('#datetimepicker1').datetimepicker({format: 'YYYY-MM-DD'});
    });
  </script>

  <br>

  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">
      <div class="form-group">

        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th><%= t('.fromcountrytab')%></th>
                <th><%= t('.tocitytab')%></th>
                <th><%= t('.departure_date')%></th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @my_itineraries.each do |itinerary| %>
              <tr>
                <td><%= ISO3166::Country.new(itinerary.country_from).name %></td>
                <td><%= itinerary.city_to %></td>
                <td><%= itinerary.departure_date %></td>
                <td><%= link_to "Delete", itinerary_path(itinerary), method: :delete, class: "btn btn-primary btn-xs" %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>

      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-4 col-lg-offset-4">
      <div class="form-group">
        <%= f.submit t('.registerbutton'), class: "btn btn-primary btn-post center-block" %>
      </div>
    </div>
  </div>

  <% end %>
  <hr class="sectionborder">
</div>

app/views/users/show.html.erb
Here is show page