config/routes.rb
Rails.application.routes.draw do


root 'top#index'

scope "/:locale", locale: /en|ja/   do

  get '' => 'top#index', as: 'top'
  get 'porter' => 'porter#top', as: 'porter_top'
  get 'help' => 'help#index', as: 'help_index'
  get 'inbox' => 'inbox#index', as: "inbox_index"
  get 'inbox/:id' => 'inbox#show', as: "inbox_personal"

  resources :messageboxes, only: [:create, :destroy]
  resources :messages, only: [:create]
  resources :demandposts do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :users, only: [:show, :edit, :update]

  # devise_scope :user do
  #   delete :sign_out, to: 'devise/session#destroy', as: :destroy_user_session
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

  devise_for :users,  controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  # , skip: [:session, :registrations]
  # devise_scope :user do
  #   post "/users/sign_in",    :to => "devise/sessions#create",   :as => 'user_session'
  #   delete "/users/sign_out", :to => "devise/sessions#destroy",  :as => 'destroy_session'
  #   get "/users/edit",        :to => "devise/registrations#edit",  :as => 'edit_user_registration'
  #   put "/users/edit",        :to => "devise/registrations#update",  :as => 'user_registration'
  #   delete "/users/edit",     :to => "devise/registrations#destroy",  :as => nil
  #   post "/users/edit",       :to => "devise/registrations#create",  :as => nil
  # end
  post 'itineraries' => 'itineraries#create', as: "itineraries"
  delete 'itineraries/:id' => 'itineraries#destroy', as: "itinerary"


end

app/models/demandpost.rb
class Demandpost < ApplicationRecord
  belongs_to :user

  validates :city_to, presence: true
  validates :country_from, presence: true
  validates :item_description, presence: true
  validates :reward_description, presence: true

end

app/controllers/demandposts_controller.rb
class DemandpostsController < ApplicationController
  before_action :set_demandpost, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :new, :create, :edit, :update, :destroy]

  # GET /demandposts
  # GET /demandposts.json
  def index
    # Currently ransack gem is used for posting research
    # from top page, params[:q] ic coming
    # just for city query
    # the search logic must be reevaluated
    @search = Demandpost.search(params[:q])
    @demandposts = @search.result.order(created_at: :desc).page params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @demandposts }
    end
  end

  # GET /demandposts/1
  # GET /demandposts/1.json
  def show
    @c = ISO3166::Country.new(@demandpost.country_from)
  end

  # GET /demandposts/new
  def new
    @demandpost = Demandpost.new
  end

  # GET /demandposts/1/edit
  def edit
  end

  # POST /demandposts
  # POST /demandposts.json
  def create
    @demandpost = Demandpost.new(demandpost_params)

    respond_to do |format|
      if @demandpost.save
        format.html { redirect_to @demandpost, notice: 'Demandpost was successfully created.' }
        format.json { render :show, status: :created, location: @demandpost }
      else
        format.html { render :new }
        format.json { render json: @demandpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /demandposts/1
  # PATCH/PUT /demandposts/1.json
  def update
    respond_to do |format|
      if @demandpost.update(demandpost_params)
        format.html { redirect_to @demandpost, notice: 'Demandpost was successfully updated.' }
        format.json { render :show, status: :ok, location: @demandpost }
      else
        format.html { render :edit }
        format.json { render json: @demandpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demandposts/1
  # DELETE /demandposts/1.json
  def destroy
    @demandpost.destroy
    respond_to do |format|
      format.html { redirect_to demandposts_url, notice: 'Demandpost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demandpost
      @demandpost = Demandpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def demandpost_params
      params.require(:demandpost).permit(:city_to, :city_from, :country_from, :expire_date, :item_description, :money_ok, :no_money_ok, :reward_description).merge(user_id: current_user.id)
    end
end

app/helpers/demandposts_helper.rb
module DemandpostsHelper
end

app/views/demandposts/_form.html.erb
<div class="body-padding">
  <%= form_with(model: demandpost, local: true, class: "form-horizontal") do |f| %>
  <% if demandpost.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(demandpost.errors.count, "error") %>
      prohibited this demandpost from being saved:</h2>
    <ul>
      <% demandpost.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="text-center">
    <h2 class="section-heading"><%= t('demandposts._form.title')%></h2>
  </div>
  <br>

  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="form-group">
          <% if current_user.home_town.blank? || current_user.name.blank?%>
          <%= link_to t('demandposts._form.editprofile'), edit_user_path(current_user), class: "btn btn-primary btn-post center-block" %>
          <% end %>
        </div>
      </div>
      <div class="col-md-6 col-md-offset-3">
        <div class="form-group">
          <%= f.label :city_to, t('demandposts._form.city_to'), class: "control-label col-md-3" %>
          <div class="col-md-6">
            <%= f.text_field :city_to, id: :city_to, class: "form-control", value: current_user.home_town %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :city_from, t('demandposts._form.country_from'), class: "control-label col-md-3" %>
          <div class="col-md-6">
            <%= f.country_select :country_from, {priority: %w(US CA), prompt: t('demandposts._form.country_placeholder')}, class: "form-control" %>
          </div>
        </div>

        <div class="form-group ">
          <%= f.label :expire_date, t('demandposts._form.expire_date'), class: "control-label col-md-3" %>
          <div class="col-md-6">
            <div class="input-group date" id='datetimepicker1'>
              <%= f.text_field :expire_date,  class: "form-control", placeholder: "Expire Date" %>
              <span class="input-group-addon">
                <span class="glyphicon glyphicon-calendar"></span>
              </span>
            </div>
          </div>
        </div>

        <script type="text/javascript">
          $(function () {
            $('#datetimepicker1').datetimepicker({
              format: 'YYYY-MM-DD'
            });
          });
        </script>

        <hr>

        <div class="form-group">
          <%= f.label :item_description, t('demandposts._form.item_description'), class: "control-label col-md-3" %>
          <div class="col-md-9">
            <%= f.text_area :item_description, class: "form-control", placeholder: t('demandposts._form.item_description_placeholder') %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :money_ok, t('demandposts._form.reward_type'), class: "control-label col-md-3" %>

          <div class="col-md-9">
            <div class="checkbox-inline">
              <%= f.check_box :money_ok %><%= t('demandposts._form.money_ok')%>
            </div>
            <div class="checkbox-inline">
              <%= f.check_box :no_money_ok %><%= t('demandposts._form.no_money_ok')%>
            </div>
          </div>
        </div>
        <br/>
        <div class="form-group">
          <%= f.label :reward_description, t('demandposts._form.reward_description'), class: "control-label col-md-3"   %>
          <div class="col-md-9">
            <%= f.text_area :reward_description, class: "form-control", placeholder: t('demandposts._form.reward_description_placeholder') %>
          </div>
        </div>
        <div class="form-group">
          <p class="fine"><%= t('demandposts._form.footercomment') %></p>
          <%= f.submit t('demandposts._form.submitbutton'), class: "btn btn-primary btn-post center-block" %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/demandposts/edit.html.erb
<div class="body-padding">
  <%= render 'form', demandpost: @demandpost %>
</div>

app/views/demandposts/index.html.erb
<div class="body-padding">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <% unless @demandposts.any? %>
          <h2>現在、条件に合うアナウンスはありません</h2>
          <h4>条件に合うリクエストが投稿されたら通知されるよう、旅行日程を登録しましょう</h4>
          <%= link_to "Register Itinerary", edit_user_path(current_user), class:"btn btn-primary" %>
        <% else %>
          <hr class="blackborder">
          <% @demandposts.each do |demandpost| %>
          <a href="<%= url_for(demandpost) %>" class="post">
            <div class="row">
              <div class="col-md-4">
                <%= image_tag demandpost.user.avatar.url(:medium), class: "avatarmedium center-block"%>
                <div class="text-center">
                  <div class="profile-font-name"><%= demandpost.user.name %></div>
                  <div class="profile-font-town"><%= demandpost.city_to %></div>
                </div>
              </div>
              <div class="col-md-8">
                <div>
                  <div class="post-font-subtitle"><%= t('.country_from') %></div>
                  <div class="post-font-detail"><%= ISO3166::Country.new(demandpost.country_from).name %></div>
                  <div class="post-font-subtitle"><%= t('.item_description') %></div>
                  <div class="post-font-detail"><%= demandpost.item_description %></div>
                  <div class="post-font-subtitle"><%= t('.reward_type_header') %></div>
                  <div class="post-font-detail">
                    <% if demandpost.money_ok == true && demandpost.no_money_ok == true %>
                    <%= t('.reward_type1') %>
                    <% elsif demandpost.money_ok == true %>
                    <%= t('.reward_type2') %>
                    <% elsif demandpost.no_money_ok == true %>
                    <%= t('.reward_type3') %>
                    <% end %>
                  </div>
                  <div class="post-font-subtitle"><%= t('.reward_description') %></div>
                  <div class="post-font-detail"><%= demandpost.reward_description %></div>
                </div>
              </div>
            </div>
            <hr class="blackborder">
            <% end %>

            <%= paginate @demandposts %>

          <% end%>          
        </div>
      </div>
    </div>
  </div>

app/views/demandposts/new.html.erb
<div class="body-padding">
  <%= render 'form', demandpost: @demandpost %>
</div>

app/views/demandposts/show.html.erb
<div class="body-padding">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <% if @demandpost.user_id != current_user.id %>
        <h2><%= t('.title_porter') %></h2>
      <% else %>
        <h2><%= t('.title_announcer') %></h2>
        <% end %>
        <hr class="blackborder">
        <div class="row">
          <div class="col-md-4">
            <div class="col-md-12">
              <%= image_tag @demandpost.user.avatar.url(:medium), class: "avatarmedium center-block" %>
            </div>
            <div class="text-center col-md-12">
              <div class="profile-font-name"><%= @demandpost.user.name %></div>
              <div class="profile-font-town"><%= @demandpost.city_to %></div>
            </div>
          </div>
          <div class="col-md-8">
            <div>
              <div class="post-font-subtitle"><%= t('.country_from') %></div>
              <div class="post-font-detail"><%= @c.name %></div>
              <div class="post-font-subtitle"><%= t('.item_description') %></div>
              <div class="post-font-detail"><%= @demandpost.item_description %></div>
              <div class="post-font-subtitle"><%= t('.reward_type_header') %></div>
              <div class="post-font-detail">
                <% if @demandpost.money_ok == true && @demandpost.no_money_ok == true %>
                <%= t('.reward_type1') %>
                <% elsif @demandpost.money_ok == true %>
                <%= t('.reward_type2') %>
                <% elsif @demandpost.no_money_ok == true %>
                <%= t('.reward_type3') %>
                <% end %>
              </div>
              <div class="post-font-subtitle"><%= t('.reward_description') %></div>
              <div class="post-font-detail"><%= @demandpost.reward_description %></div>
            </div>
          </div>
        </div>

        <hr class="blackborder">
        <% if @demandpost.user_id != current_user.id %>
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= form_tag(messages_path(user_to_id: @demandpost.user.id, initial_message: true), method: :post) do %>
              <textarea type="text" , name="content" cols="30" rows="5" class="form-control" , placeholder= "<%= t('.first_message_placeholder') %>"></textarea>
              <br/>
              <%= submit_tag t('.first_message_button'), class:  "btn btn-primary btn-post center-block" %>
              <% end %>
            </div>
          </div>
        </div>
      <% else %>
        <div class="row">
          <div class="col-md-12">
            <div class="form-group">
              <%= link_to t('.back_button'), root_path, class: "btn btn-primary" %>
              <%= link_to t('.edit_button'), edit_demandpost_path(@demandpost), class: "btn btn-primary" %>
              <%= link_to t('.unpost_button'), demandpost_path(@demandpost), method: :delete, class: "btn btn-primary" %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>