config/routes.rb
Rails.application.routes.draw do


root 'top#index'

scope "/:locale", locale: /en|ja/   do

  get '' => 'top#index', as: 'top'
  get 'porter' => 'porter#top', as: 'porter_top'
  get 'help' => 'help#index', as: 'help_index'
  get 'inbox' => 'inbox#index', as: "inbox_index"
  get 'inbox/:id' => 'inbox#show', as: "inbox_personal"

  resources :messageboxes, only: [:create, :destroy]
  resources :messages, only: [:create]
  resources :demandposts do
    get 'page/:page', :action => :index, :on => :collection
  end

  resources :users, only: [:show, :edit, :update]

  # devise_scope :user do
  #   delete :sign_out, to: 'devise/session#destroy', as: :destroy_user_session
  # end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  end

  devise_for :users,  controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  # , skip: [:session, :registrations]
  # devise_scope :user do
  #   post "/users/sign_in",    :to => "devise/sessions#create",   :as => 'user_session'
  #   delete "/users/sign_out", :to => "devise/sessions#destroy",  :as => 'destroy_session'
  #   get "/users/edit",        :to => "devise/registrations#edit",  :as => 'edit_user_registration'
  #   put "/users/edit",        :to => "devise/registrations#update",  :as => 'user_registration'
  #   delete "/users/edit",     :to => "devise/registrations#destroy",  :as => nil
  #   post "/users/edit",       :to => "devise/registrations#create",  :as => nil
  # end
  post 'itineraries' => 'itineraries#create', as: "itineraries"
  delete 'itineraries/:id' => 'itineraries#destroy', as: "itinerary"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/demandpost.rb
class Demandpost < ApplicationRecord
  belongs_to :user

  validates :city_to, presence: true
  validates :country_from, presence: true
  validates :item_description, presence: true
  validates :reward_description, presence: true

end

app/models/itinerary.rb
class Itinerary < ApplicationRecord
  belongs_to :user
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user_from, class_name: 'User'
  belongs_to :user_to, class_name: 'User'
  belongs_to :messagebox
  
  validates :content, presence: true
  validates :user_from_id, presence: true
  validates :user_to_id, presence: true
end

app/models/messagebox.rb
class Messagebox < ApplicationRecord
  has_many :messages
  has_many :usercontacts
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :confirmable

  has_many :demandposts, dependent: :destroy

  has_many :send_messages, class_name: 'Message', foreign_key: 'user_from_id'
  has_many :recieve_messages, class_name: 'Message', foreign_key: 'user_to_id'

  has_many :usercontacts
  has_many :itineraries

  attr_reader :avatar_remote_url
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>"}, default_url: "profile-default.jpg"
  validates_attachment_content_type :avatar, content_type: ["image/jpg","image/jpeg","image/png"]


  def avatar_remote_url=(url_value)
    self.avatar = URI.parse(url_value)
    # Assuming url_value is http://example.com/photos/face.png
    # avatar_file_name == "face.png"
    # avatar_content_type == "image/png"
    @avatar_remote_url = url_value
  end

  def self.find_for_oauth(auth)
    user = User.where(uid: auth.uid, provider: auth.provider).first

    unless user
      user = User.create(
        uid:      auth.uid,
        provider: auth.provider,
        email:    auth.info.email,
        password: Devise.friendly_token[0, 20],
        confirmed_at: Time.now.utc,
        confirmation_token: nil,
        name:     auth.info.name,
        avatar: auth.info.image
      )
    end

    user
  end

  private

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

end

app/models/usercontact.rb
class Usercontact < ApplicationRecord
  belongs_to :user
  belongs_to :contacted, class_name: 'User'
  belongs_to :messagebox
  has_many :messages, through: :messagebox

  validates :user_id, presence: true
  validates :contacted, presence: true
end

app/controllers/help_controller.rb
class HelpController < ApplicationController
  def index
  end
end

app/controllers/inbox_controller.rb
class InboxController < ApplicationController
  before_action :authenticate_user!

  def index
    usercontacts = Usercontact.where(user_id: current_user.id).includes(:messages, :contacted)
    @users = []
    @lastmessages = []
    usercontacts.each do |usercontact|
      @lastmessages << usercontact.messages.order(created_at: :desc).first
      @users << usercontact.contacted
    end
    @array = @users.zip(@lastmessages)
  end

  def show
    # check if the user has the access to this messagebox
    usercontact = Usercontact.find_by(messagebox_id: params[:id], user_id: current_user.id)
    if usercontact.nil?
      redirect_to root_path
    else
      @messages = Message.where(messagebox_id: params[:id]).order(created_at: :desc)
      @user = Usercontact.find_by(messagebox_id: params[:id], user_id: current_user.id).contacted
    end
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
    if user_signed_in?
      @demandposts = Demandpost.last(5)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/demandposts_helper.rb
module DemandpostsHelper
end

app/helpers/help_helper.rb
module HelpHelper
end

app/helpers/inbox_helper.rb
module InboxHelper
end

app/helpers/itineraries_helper.rb
module ItinerariesHelper
end

app/helpers/messageboxes_helper.rb
module MessageboxesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/porter_helper.rb
module PorterHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Courcie</title>
    <link rel="icon" href="<%= asset_path "profile-default.jpg" %>">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"></script>

    <!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/ -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<%= escape_javascript(ENV['GMAP_KYE'])%>&libraries=places"></script>

    <!-- Custom Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Normally we should gather up following javascript code into *.js
    But doing that I got following error: Uncaught ReferenceError: google is not defined
    I did not know why this error does not occur writing in here. Please correct later
    -->
    <script type="text/javascript">
      function initialize(){
          var input_from = document.getElementById('city_from');
          var input_to = document.getElementById('city_to');

          var options = {
              types: ['(cities)'],
          };
          autocomplete = new google.maps.places.Autocomplete( input_from, options);
          autocomplete = new google.maps.places.Autocomplete( input_to, options);
      }

      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
</head>

<body  onload="initialize()">

<% if user_signed_in? %>


<nav id="mainNav" class="navbar navbar-default-signed navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        Menu
        <i class="fa fa-bars"></i>
      </button>
      <%= link_to "Courcie", top_path, class: "navbar-brand page-scroll"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span class="sr-only">Toggle navigation</span><i class="fa fa-language fa-lg"></i>
          </a>
          <ul class="dropdown-menu">
            <% I18n.available_locales.each do |locale| %>
              <% if locale == :en %>
                <% lang = "English" %>
              <% elsif locale == :ja %>
                <% lang = "日本語" %>
              <% end %>
              <li><%= link_to(lang, url_for(locale: locale)) %></li>
            <% end %>
          </ul>
        </li>
        <li><%= link_to t('.porterlink'), porter_top_path %></li>
        <li><%= link_to t('.favorlink'), new_demandpost_path %></li>
        <li><%= link_to t('.messagelink'), inbox_index_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle avatar" data-toggle="dropdown">
            <span><%= image_tag current_user.avatar.url(:medium), class: "avatarmicro"%></span>

          </a>
          <ul id="login-dp-signed" class="dropdown-menu">
            <li><%= link_to t('.logoutlink'), destroy_user_session_path, method: :delete %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to t('.profilelink'), edit_user_path(current_user) %></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>


<% else %>

<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        Menu
        <i class="fa fa-bars"></i>
      </button>
      <%= link_to "Courcie", top_path, class: "navbar-brand page-scroll"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <span class="sr-only">Toggle navigation</span><i class="fa fa-language fa-lg"></i>
          </a>
          <ul class="dropdown-menu">
            <% I18n.available_locales.each do |locale| %>
              <% if locale == :en %>
                <% lang = "English" %>
              <% elsif locale == :ja %>
                <% lang = "日本語" %>
              <% end %>
              <li><%= link_to(lang, url_for(locale: locale)) %></li>
            <% end %>
          </ul>
        </li>
        <li><%= link_to t('.porterlink'), porter_top_path %></li>
        <li>
            <a role="button" data-toggle="modal" data-target="#signup-modal" data-backdrop="static" data-controls-modal="signup-modal">
              <b>Sign Up</b>
            </a>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <b>Login</b>
            <span class="caret"></span>
          </a>
          <ul id="login-dp" class="dropdown-menu">
            <li>
              <div class="row">
                <div class="col-md-12">
                  Login via
                  <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                  <div class="social-buttons">
                    <a href="<%= omniauth_authorize_path(resource_name, "facebook") %>" class="btn btn-fb">
                      <i class="fa fa-facebook"></i>
                      Facebook</a>
                  </div>
                  or

                  <form class="form" role="form" method="post" action="login" accept-charset="UTF-8" id="login-nav">
                    <div class="form-group">
                      <div class="field">
                        <%= f.label :email, "Email address", class: "sr-only" %>
                        <%= f.email_field :email, class: "form-control", autofocus: true, placeholder: "Email address" %>
                      </div>
                    </div>
                    <div class="form-group">

                      <%= f.label :password, "password", class: "sr-only"%>
                      <%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "Password" %>

                      <div class="help-block text-right">
                        <a href="">Forget the password ?</a>
                      </div>
                    </div>
                    <div class="form-group">
                      <%= f.submit "Sign in", class: "btn btn-primary btn-block" %>
                    </div>

                    <div class="form-group">
                      <% if devise_mapping.rememberable? %>
                      <%= f.check_box :remember_me %>
                      Keep Log in


                      <% end %>
                    </div>
                  </form>
                  <% end %>

                </div>
                <div class="bottom text-center">
                  New here ?
                  <a role="button" data-toggle="modal" data-target="#signup-modal" data-backdrop="static" data-controls-modal="signup-modal">
                    <b>Join Us</b>
                  </a>
                </div>
              </div>
            </li>
          </ul>
        </li>

      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

<% end %>
<div class="top-space">
</div>
  <%= yield %>
</body>


<!-- Footer -->
<footer>
    <div class="container text-center">
        <p>Copyright &copy; Courcie 2017</p>
    </div>
</footer>

</html>